package handler

import (
	"log"
	"regexp"
	"strings"
)

type GovernanceResult struct {
	Allowed      bool
	ModifiedText string
	RefusalMsg   string
	Disclaimer   string
	RuleID       string
}

func EvaluateConstitution(prompt string) GovernanceResult {
	res := GovernanceResult{
		Allowed:      true,
		ModifiedText: prompt,
	}

	// 🛡️ 1. DATA LOSS PREVENTION (DLP)
	patterns := map[string]string{
		"DLP_MEDICAL": `(?i)(patient_id|ssn|mrn):?\s*[0-9A-Z-]+`,
		"DLP_FINANCE": `(?i)(iban|card_number|cvv|swift):?\s*[A-Z0-9]+`,
	}

	for id, p := range patterns {
		re := regexp.MustCompile(p)
		if re.MatchString(res.ModifiedText) {
			log.Printf("🛡️ [GOVERNANCE] Rule %s Triggered", id)
			res.ModifiedText = re.ReplaceAllString(res.ModifiedText, "[REDACTED_BY_NEXUS]")
			res.RuleID = id
		}
	}

	// 🛡️ 2. SECURITY GATE (Anti-Jailbreak)
	jailbreakTerms := []string{"ignore all previous instructions", "system prompt leak", "bypass safety"}
	for _, term := range jailbreakTerms {
		if strings.Contains(strings.ToLower(prompt), term) {
			log.Printf("🚫 [GOVERNANCE] Rule SEC_JAILBREAK Triggered")
			return GovernanceResult{
				Allowed:    false,
				RefusalMsg: "Nexus Sovereign Shield: Protocol violation. Instructional override detected.",
				RuleID:     "SEC_JAILBREAK",
			}
		}
	}

	// 🛡️ 3. LEGAL COMPLIANCE (Disclaimer Detection)
	riskyTerms := []string{"bitcoin", "invest", "prescription", "stock"}
	for _, term := range riskyTerms {
		if strings.Contains(strings.ToLower(prompt), term) {
			log.Printf("⚖️ [GOVERNANCE] Rule LEG_ADVICE Triggered")
			res.Disclaimer = "\n\n[Nexus Protocol Disclaimer]: This response is generated by AI. Consult a certified professional for medical or financial decisions."
			res.RuleID = "LEG_ADVICE"
		}
	}

	return res
}