

package handler

import (
	"log"
	"regexp"
	"strings"
)

type GovernanceResult struct {
	Allowed      bool
	ModifiedText string
	RefusalMsg   string
	Disclaimer   string
	RuleID       string
}

func EvaluateConstitution(prompt string) GovernanceResult {
	res := GovernanceResult{
		Allowed:      true,
		ModifiedText: prompt,
		RuleID:       "NONE",
	}

	// 🛡️ 1. INFRASTRUCTURE & CYBER SECURITY (Hard Refusal)
	// Targets: WiFi hacking, Firewall bypassing, and unauthorized access
	infraPatterns := map[string]string{
		"SEC_INFRA": `(?i)(bypass|hack|exploit|firewall|proxy|vpn|password|wifi|auth|admin)\s*(university|lpu|network|server|router)`,
		"SEC_NET":   `(?i)(sql injection|cross-site scripting|brute force|reverse shell|payload)`,
	}

	for id, p := range infraPatterns {
		re := regexp.MustCompile(p)
		if re.MatchString(prompt) {
			log.Printf("🚫 [GOVERNANCE] Rule %s Blocked Attempt", id)
			return GovernanceResult{
				Allowed:    false,
				RefusalMsg: "Nexus Sovereign Shield: Security Protocol Violation. Request targeting infrastructure or unauthorized access is strictly prohibited.",
				RuleID:     id,
			}
		}
	}

	// 🛡️ 2. DATA LOSS PREVENTION (DLP) & PII (Redaction)
	// Protects LPU Student IDs, Emails, and Financial Data
	dlpPatterns := map[string]string{
		"DLP_MEDICAL": `(?i)(patient_id|ssn|mrn):?\s*[0-9A-Z-]+`,
		"DLP_FINANCE": `(?i)(iban|card_number|cvv|swift):?\s*[A-Z0-9]+`,
		"DLP_STUDENT": `(?i)(registration_number|roll_number|lpu_id):?\s*\d{8}`,
		"DLP_EMAIL":   `[a-zA-Z0-9._%+-]+@lpu\.in`,
	}

	for id, p := range dlpPatterns {
		re := regexp.MustCompile(p)
		if re.MatchString(res.ModifiedText) {
			log.Printf("🛡️ [GOVERNANCE] Rule %s Redacted", id)
			res.ModifiedText = re.ReplaceAllString(res.ModifiedText, "[REDACTED_SENSITIVE_DATA]")
			res.RuleID = id
		}
	}

	// 🛡️ 3. ANTI-JAILBREAK GATE (Hard Refusal)
	jailbreakTerms := []string{
		"ignore all previous instructions", 
		"system prompt leak", 
		"bypass safety", 
		"developer mode", 
		"dan mode",
	}
	promptLower := strings.ToLower(prompt)
	for _, term := range jailbreakTerms {
		if strings.Contains(promptLower, term) {
			log.Printf("🚫 [GOVERNANCE] Rule SEC_JAILBREAK Blocked")
			return GovernanceResult{
				Allowed:    false,
				RefusalMsg: "Nexus Sovereign Shield: Instructional override detected. Integrity preserved.",
				RuleID:     "SEC_JAILBREAK",
			}
		}
	}

	// 🛡️ 4. LEGAL & FINANCIAL COMPLIANCE (Disclaimers)
	riskyTerms := []string{"bitcoin", "invest", "prescription", "stock", "medical advice", "legal advice"}
	for _, term := range riskyTerms {
		if strings.Contains(promptLower, term) {
			log.Printf("⚖️ [GOVERNANCE] Rule LEG_ADVICE Triggered")
			res.Disclaimer = "\n\n[Nexus Protocol Disclaimer]: This response is generated by AI. Consult a certified professional for medical, legal, or financial decisions."
			res.RuleID = "LEG_ADVICE"
		}
	}

	return res
}


